name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    env:
      JULIA_NUM_THREADS: 2
      MUJOCO_KEY: ${{ secrets.MUJOCO_KEY }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        julia-version: ['1.3', '1.4']
        julia-arch: [x64]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Add registry
        run: |
          julia -e 'using Pkg; Registry.add(RegistrySpec(url = "https://github.com/Lyceum/LyceumRegistry.git"))'
          julia -e 'using Pkg; Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"))'
        shell: bash
      - name: Install Run.jl
        run: |
          julia -e 'using Pkg; pkg"add https://github.com/tkf/Run.jl"'
        shell: bash
      - name: Prepare environment
        run: julia -e 'using Run; Run.prepare_test()'
      - name: Run tests
        run:  julia -e 'using Run; Run.test()'
